version: "3"
services:
    ghost:
        image: ghost:1-alpine
        restart: always
        ports:
          - 127.0.0.1:8080:2368
        volumes:
          - ./blog/data/ghost:/var/lib/ghost/content
        environment:
          - url=https:/" " //COLOCAR DOMINIO
          - VIRTUAL_HOST=" " //COLOCAR DOMINIO
          - LETSENCRYPT_HOST=" " //COLOCAR DOMINIO
          - LETSENCRYPT_EMAIL=" "//COLOCAR CORREO ELECTRONICO

networks:
  default:
    external:
      name: nginx-proxy
